[build]
  command = "ng build"
  functions = "netlify/functions"
  publish = "dist/melodica/browser"

[dev]
  functions = "netlify/functions"
  
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true